/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_label = 1,
  anon_sym_COLON = 2,
  anon_sym_jump = 3,
  anon_sym_call = 4,
  sym_return_statement = 5,
  anon_sym_pause = 6,
  anon_sym_scene = 7,
  anon_sym_show = 8,
  anon_sym_hide = 9,
  anon_sym_menu = 10,
  anon_sym_DOLLAR = 11,
  anon_sym_python = 12,
  anon_sym_init = 13,
  sym_indented_block = 14,
  sym_python_content = 15,
  sym_identifier = 16,
  anon_sym_DQUOTE = 17,
  aux_sym_string_token1 = 18,
  anon_sym_SQUOTE = 19,
  aux_sym_string_token2 = 20,
  sym_comment = 21,
  sym_number = 22,
  sym_source_file = 23,
  sym__statement = 24,
  sym_label_statement = 25,
  sym_say_statement = 26,
  sym_jump_statement = 27,
  sym_call_statement = 28,
  sym_pause_statement = 29,
  sym_scene_statement = 30,
  sym_show_statement = 31,
  sym_hide_statement = 32,
  sym_menu_statement = 33,
  sym_python_line = 34,
  sym_python_block = 35,
  sym_init_statement = 36,
  sym_image_name = 37,
  sym_string = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_image_name_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_label] = "label",
  [anon_sym_COLON] = ":",
  [anon_sym_jump] = "jump",
  [anon_sym_call] = "call",
  [sym_return_statement] = "return_statement",
  [anon_sym_pause] = "pause",
  [anon_sym_scene] = "scene",
  [anon_sym_show] = "show",
  [anon_sym_hide] = "hide",
  [anon_sym_menu] = "menu",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_python] = "python",
  [anon_sym_init] = "init",
  [sym_indented_block] = "indented_block",
  [sym_python_content] = "python_content",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_label_statement] = "label_statement",
  [sym_say_statement] = "say_statement",
  [sym_jump_statement] = "jump_statement",
  [sym_call_statement] = "call_statement",
  [sym_pause_statement] = "pause_statement",
  [sym_scene_statement] = "scene_statement",
  [sym_show_statement] = "show_statement",
  [sym_hide_statement] = "hide_statement",
  [sym_menu_statement] = "menu_statement",
  [sym_python_line] = "python_line",
  [sym_python_block] = "python_block",
  [sym_init_statement] = "init_statement",
  [sym_image_name] = "image_name",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_image_name_repeat1] = "image_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_label] = anon_sym_label,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_jump] = anon_sym_jump,
  [anon_sym_call] = anon_sym_call,
  [sym_return_statement] = sym_return_statement,
  [anon_sym_pause] = anon_sym_pause,
  [anon_sym_scene] = anon_sym_scene,
  [anon_sym_show] = anon_sym_show,
  [anon_sym_hide] = anon_sym_hide,
  [anon_sym_menu] = anon_sym_menu,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_python] = anon_sym_python,
  [anon_sym_init] = anon_sym_init,
  [sym_indented_block] = sym_indented_block,
  [sym_python_content] = sym_python_content,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_label_statement] = sym_label_statement,
  [sym_say_statement] = sym_say_statement,
  [sym_jump_statement] = sym_jump_statement,
  [sym_call_statement] = sym_call_statement,
  [sym_pause_statement] = sym_pause_statement,
  [sym_scene_statement] = sym_scene_statement,
  [sym_show_statement] = sym_show_statement,
  [sym_hide_statement] = sym_hide_statement,
  [sym_menu_statement] = sym_menu_statement,
  [sym_python_line] = sym_python_line,
  [sym_python_block] = sym_python_block,
  [sym_init_statement] = sym_init_statement,
  [sym_image_name] = sym_image_name,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_image_name_repeat1] = aux_sym_image_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_label] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jump] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_call] = {
    .visible = true,
    .named = false,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_pause] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_scene] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_show] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_hide] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_menu] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_python] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_init] = {
    .visible = true,
    .named = false,
  },
  [sym_indented_block] = {
    .visible = true,
    .named = true,
  },
  [sym_python_content] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_label_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_say_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_call_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_pause_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_scene_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_show_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_hide_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_menu_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_python_line] = {
    .visible = true,
    .named = true,
  },
  [sym_python_block] = {
    .visible = true,
    .named = true,
  },
  [sym_init_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_image_name] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_image_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '\r') SKIP(11);
      if (lookahead == '"') ADVANCE(72);
      if (lookahead == '#') ADVANCE(80);
      if (lookahead == '$') ADVANCE(24);
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'c') ADVANCE(33);
      if (lookahead == 'h') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(55);
      if (lookahead == 'j') ADVANCE(66);
      if (lookahead == 'l') ADVANCE(34);
      if (lookahead == 'm') ADVANCE(42);
      if (lookahead == 'p') ADVANCE(35);
      if (lookahead == 'r') ADVANCE(43);
      if (lookahead == 's') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(5);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == '\n') SKIP(7);
      if (lookahead == '\r') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') SKIP(12);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') SKIP(12);
      if (lookahead == '\r') SKIP(11);
      if (lookahead == '"') ADVANCE(72);
      if (lookahead == '#') ADVANCE(80);
      if (lookahead == '$') ADVANCE(24);
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'c') ADVANCE(33);
      if (lookahead == 'h') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(55);
      if (lookahead == 'j') ADVANCE(66);
      if (lookahead == 'l') ADVANCE(34);
      if (lookahead == 'm') ADVANCE(42);
      if (lookahead == 'p') ADVANCE(35);
      if (lookahead == 'r') ADVANCE(43);
      if (lookahead == 's') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_label);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_jump);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_call);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_return_statement);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_pause);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_scene);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_show);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_hide);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_menu);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_python);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_init);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_indented_block);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_indented_block);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_indented_block);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_indented_block);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_python_content);
      if (lookahead == '\r') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_python_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(67);
      if (lookahead == 'y') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(44);
      if (lookahead == 'h') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'w') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '\r') ADVANCE(74);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(75);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(75);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead == '\r') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\n') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 77},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 73},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_label] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_jump] = ACTIONS(1),
    [anon_sym_call] = ACTIONS(1),
    [sym_return_statement] = ACTIONS(1),
    [anon_sym_pause] = ACTIONS(1),
    [anon_sym_scene] = ACTIONS(1),
    [anon_sym_show] = ACTIONS(1),
    [anon_sym_hide] = ACTIONS(1),
    [anon_sym_menu] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_python] = ACTIONS(1),
    [anon_sym_init] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym__statement] = STATE(2),
    [sym_label_statement] = STATE(2),
    [sym_say_statement] = STATE(2),
    [sym_jump_statement] = STATE(2),
    [sym_call_statement] = STATE(2),
    [sym_pause_statement] = STATE(2),
    [sym_scene_statement] = STATE(2),
    [sym_show_statement] = STATE(2),
    [sym_hide_statement] = STATE(2),
    [sym_menu_statement] = STATE(2),
    [sym_python_line] = STATE(2),
    [sym_python_block] = STATE(2),
    [sym_init_statement] = STATE(2),
    [sym_string] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_label] = ACTIONS(5),
    [anon_sym_jump] = ACTIONS(7),
    [anon_sym_call] = ACTIONS(9),
    [sym_return_statement] = ACTIONS(11),
    [anon_sym_pause] = ACTIONS(13),
    [anon_sym_scene] = ACTIONS(15),
    [anon_sym_show] = ACTIONS(17),
    [anon_sym_hide] = ACTIONS(19),
    [anon_sym_menu] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [anon_sym_python] = ACTIONS(25),
    [anon_sym_init] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [sym_comment] = ACTIONS(35),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym_label_statement] = STATE(3),
    [sym_say_statement] = STATE(3),
    [sym_jump_statement] = STATE(3),
    [sym_call_statement] = STATE(3),
    [sym_pause_statement] = STATE(3),
    [sym_scene_statement] = STATE(3),
    [sym_show_statement] = STATE(3),
    [sym_hide_statement] = STATE(3),
    [sym_menu_statement] = STATE(3),
    [sym_python_line] = STATE(3),
    [sym_python_block] = STATE(3),
    [sym_init_statement] = STATE(3),
    [sym_string] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_label] = ACTIONS(5),
    [anon_sym_jump] = ACTIONS(7),
    [anon_sym_call] = ACTIONS(9),
    [sym_return_statement] = ACTIONS(39),
    [anon_sym_pause] = ACTIONS(13),
    [anon_sym_scene] = ACTIONS(15),
    [anon_sym_show] = ACTIONS(17),
    [anon_sym_hide] = ACTIONS(19),
    [anon_sym_menu] = ACTIONS(21),
    [anon_sym_DOLLAR] = ACTIONS(23),
    [anon_sym_python] = ACTIONS(25),
    [anon_sym_init] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(33),
    [sym_comment] = ACTIONS(41),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_label_statement] = STATE(3),
    [sym_say_statement] = STATE(3),
    [sym_jump_statement] = STATE(3),
    [sym_call_statement] = STATE(3),
    [sym_pause_statement] = STATE(3),
    [sym_scene_statement] = STATE(3),
    [sym_show_statement] = STATE(3),
    [sym_hide_statement] = STATE(3),
    [sym_menu_statement] = STATE(3),
    [sym_python_line] = STATE(3),
    [sym_python_block] = STATE(3),
    [sym_init_statement] = STATE(3),
    [sym_string] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_label] = ACTIONS(45),
    [anon_sym_jump] = ACTIONS(48),
    [anon_sym_call] = ACTIONS(51),
    [sym_return_statement] = ACTIONS(54),
    [anon_sym_pause] = ACTIONS(57),
    [anon_sym_scene] = ACTIONS(60),
    [anon_sym_show] = ACTIONS(63),
    [anon_sym_hide] = ACTIONS(66),
    [anon_sym_menu] = ACTIONS(69),
    [anon_sym_DOLLAR] = ACTIONS(72),
    [anon_sym_python] = ACTIONS(75),
    [anon_sym_init] = ACTIONS(78),
    [sym_identifier] = ACTIONS(81),
    [anon_sym_DQUOTE] = ACTIONS(84),
    [anon_sym_SQUOTE] = ACTIONS(87),
    [sym_comment] = ACTIONS(90),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    STATE(6), 1,
      aux_sym_image_name_repeat1,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(95), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [25] = 3,
    ACTIONS(101), 1,
      sym_number,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(99), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [50] = 4,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(6), 1,
      aux_sym_image_name_repeat1,
    ACTIONS(103), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(105), 11,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
  [77] = 2,
    ACTIONS(110), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(112), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [99] = 2,
    ACTIONS(114), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(116), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [121] = 2,
    ACTIONS(118), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(120), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [143] = 2,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(124), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [165] = 2,
    ACTIONS(126), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(128), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [187] = 2,
    ACTIONS(130), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(132), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [209] = 2,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(136), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [231] = 2,
    ACTIONS(138), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(140), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [253] = 2,
    ACTIONS(142), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(144), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [275] = 2,
    ACTIONS(146), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(148), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [297] = 2,
    ACTIONS(150), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(152), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [319] = 2,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(156), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [341] = 2,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(160), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [363] = 2,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(164), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [385] = 2,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(168), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [407] = 2,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      anon_sym_DOLLAR,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      sym_comment,
    ACTIONS(172), 12,
      anon_sym_label,
      anon_sym_jump,
      anon_sym_call,
      sym_return_statement,
      anon_sym_pause,
      anon_sym_scene,
      anon_sym_show,
      anon_sym_hide,
      anon_sym_menu,
      anon_sym_python,
      anon_sym_init,
      sym_identifier,
  [429] = 3,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(4), 1,
      aux_sym_image_name_repeat1,
    STATE(13), 1,
      sym_image_name,
  [439] = 3,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(4), 1,
      aux_sym_image_name_repeat1,
    STATE(14), 1,
      sym_image_name,
  [449] = 3,
    ACTIONS(31), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      anon_sym_SQUOTE,
    STATE(17), 1,
      sym_string,
  [459] = 3,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(4), 1,
      aux_sym_image_name_repeat1,
    STATE(15), 1,
      sym_image_name,
  [469] = 3,
    ACTIONS(176), 1,
      anon_sym_COLON,
    ACTIONS(178), 1,
      anon_sym_python,
    ACTIONS(180), 1,
      sym_number,
  [479] = 1,
    ACTIONS(182), 1,
      anon_sym_COLON,
  [483] = 1,
    ACTIONS(184), 1,
      aux_sym_string_token2,
  [487] = 1,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
  [491] = 1,
    ACTIONS(188), 1,
      sym_indented_block,
  [495] = 1,
    ACTIONS(190), 1,
      sym_python_content,
  [499] = 1,
    ACTIONS(192), 1,
      sym_indented_block,
  [503] = 1,
    ACTIONS(194), 1,
      sym_indented_block,
  [507] = 1,
    ACTIONS(196), 1,
      anon_sym_COLON,
  [511] = 1,
    ACTIONS(198), 1,
      anon_sym_python,
  [515] = 1,
    ACTIONS(200), 1,
      sym_identifier,
  [519] = 1,
    ACTIONS(202), 1,
      anon_sym_DQUOTE,
  [523] = 1,
    ACTIONS(202), 1,
      anon_sym_SQUOTE,
  [527] = 1,
    ACTIONS(204), 1,
      sym_identifier,
  [531] = 1,
    ACTIONS(206), 1,
      anon_sym_COLON,
  [535] = 1,
    ACTIONS(208), 1,
      sym_indented_block,
  [539] = 1,
    ACTIONS(210), 1,
      anon_sym_COLON,
  [543] = 1,
    ACTIONS(212), 1,
      anon_sym_COLON,
  [547] = 1,
    ACTIONS(214), 1,
      aux_sym_string_token1,
  [551] = 1,
    ACTIONS(216), 1,
      sym_indented_block,
  [555] = 1,
    ACTIONS(218), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 25,
  [SMALL_STATE(6)] = 50,
  [SMALL_STATE(7)] = 77,
  [SMALL_STATE(8)] = 99,
  [SMALL_STATE(9)] = 121,
  [SMALL_STATE(10)] = 143,
  [SMALL_STATE(11)] = 165,
  [SMALL_STATE(12)] = 187,
  [SMALL_STATE(13)] = 209,
  [SMALL_STATE(14)] = 231,
  [SMALL_STATE(15)] = 253,
  [SMALL_STATE(16)] = 275,
  [SMALL_STATE(17)] = 297,
  [SMALL_STATE(18)] = 319,
  [SMALL_STATE(19)] = 341,
  [SMALL_STATE(20)] = 363,
  [SMALL_STATE(21)] = 385,
  [SMALL_STATE(22)] = 407,
  [SMALL_STATE(23)] = 429,
  [SMALL_STATE(24)] = 439,
  [SMALL_STATE(25)] = 449,
  [SMALL_STATE(26)] = 459,
  [SMALL_STATE(27)] = 469,
  [SMALL_STATE(28)] = 479,
  [SMALL_STATE(29)] = 483,
  [SMALL_STATE(30)] = 487,
  [SMALL_STATE(31)] = 491,
  [SMALL_STATE(32)] = 495,
  [SMALL_STATE(33)] = 499,
  [SMALL_STATE(34)] = 503,
  [SMALL_STATE(35)] = 507,
  [SMALL_STATE(36)] = 511,
  [SMALL_STATE(37)] = 515,
  [SMALL_STATE(38)] = 519,
  [SMALL_STATE(39)] = 523,
  [SMALL_STATE(40)] = 527,
  [SMALL_STATE(41)] = 531,
  [SMALL_STATE(42)] = 535,
  [SMALL_STATE(43)] = 539,
  [SMALL_STATE(44)] = 543,
  [SMALL_STATE(45)] = 547,
  [SMALL_STATE(46)] = 551,
  [SMALL_STATE(47)] = 555,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_name, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image_name, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pause_statement, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pause_statement, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_image_name_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_image_name_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_image_name_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_block, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_block, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_init_statement, 5, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_init_statement, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say_statement, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say_statement, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_statement, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_statement, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_statement, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_statement, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pause_statement, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pause_statement, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scene_statement, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scene_statement, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_show_statement, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_show_statement, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hide_statement, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hide_statement, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_line, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_line, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say_statement, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say_statement, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_statement, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label_statement, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_menu_statement, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_menu_statement, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_init_statement, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_init_statement, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_init_statement, 4, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_init_statement, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [186] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_renpy(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "renpy",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
